### PR TITLE
Add support for python 3.7 and Django 3.2

### PR DESCRIPTION
**Pull request by victor-castellanos**
- Remove support for previous versions of django
- Remove support from python2
- Supports django 3.2
- Supports python 3.7
- Add Pipfile and pipenv as dependency manager
- Remove requirements.txt and tox
- Remove travis files

### CODE REVIEW

**Comment by jschroe212** [comment]
@victor-castellanos looks good. Have you tried the tests?

**Comment by victor-castellanos** [comment]
```============================= test session starts ==============================
collecting ... collected 21 items

test_backends.py::test_update_rates 
test_backends.py::test_rates_are_saved 
test_backends.py::test_rates_are_updated 
test_commands.py::test_custom_backend_used_when_specified Operations to perform:
  Synchronize unmigrated apps: djmoney_rates
  Apply all migrations: auth, contenttypes, sites
Synchronizing apps without migrations:
  Creating tables...
    Creating table djmoney_rates_ratesource
    Creating table djmoney_rates_rate
    Running deferred SQL...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
Creating test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
PASSED                               [  4%]PASSED                            [  9%]PASSED                          [ 14%]
test_commands.py::test_default_backend_used_when_not_specified 
test_utils.py::test_base_conversion_fail_when_source_does_not_exist PASSED         [ 19%]Successfully updated rates for "<class 'tests.test_commands.CustomBackend'>"
PASSED    [ 23%]Successfully updated rates for "<class 'tests.test_commands.CustomBackend'>"

test_utils.py::test_base_conversion_fail_when_currency_from_does_not_exist 
test_utils.py::test_base_conversion_fail_when_currency_to_does_not_exist 
test_utils.py::test_base_conversion_works_from_base_currency 
test_utils.py::test_base_conversion_is_working_from_other_currency 
test_utils.py::test_conversion_fail_when_source_does_not_exist 
test_utils.py::test_conversion_fail_when_currency_from_does_not_exist 
test_utils.py::test_conversion_fail_when_currency_to_does_not_exist 
test_utils.py::test_conversion_works_from_base_currency 
test_utils.py::test_conversion_is_working_from_other_currency 
test_backends.py::test_source_name_empty_is_invalid PASSED [ 28%]PASSED [ 33%]PASSED [ 38%]PASSED      [ 42%]PASSED [ 47%]PASSED    [ 52%]PASSED [ 57%]PASSED [ 61%]PASSED           [ 66%]PASSED     [ 71%]
test_backends.py::test_base_currency_empty_is_invalid 
test_backends.py::test_missing_url_error 
test_backends.py::test_missing_app_id 
test_backends.py::test_url_is_correct 
test_commands.py::test_fail_when_custom_backend_do_not_exists PASSED               [ 76%]PASSED             [ 80%]PASSED                          [ 85%]PASSED                             [ 90%]PASSED                             [ 95%]

============================== 21 passed in 1.23s ==============================

Process finished with exit code 0
PASSED     [100%]Destroying test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
```

**Comment by victor-castellanos** [comment]
@jschroe212 I'm going to timebox playing with github actions to see if as part of PRs to this fork we can at least run the tests

**Comment by victor-castellanos** [comment]
Added github action to run tests

**Pull request merged**
